export const ALL_38_XLS_ORDERS = [
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood One Daily Multivitamin - Multivitamin for Women and Men - with Real Food - Immune Support Supplement - Vitamin C & Vitamin B - Bone Health - Energy Metabolism - Vegetarian, Non-GMO - 180 Tabs",
    asin: "B00014DAJ8",
    msku: "MHB00014DAJ8",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/megafood-one-daily-180-tablets/mf-1123",
    amazonUrl: "https://www.amazon.com/dp/B00014DAJ8?th=1",
    orderNumber: "WO110074776",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "46.36",
    sellingPrice: "80.00",
    totalCost: "185.44",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Sipariş satıcı tarafından iptal edildi",
    problemResult: "Para iadesi kart ekstresine yansıdı",
    refundAmount: "185.44",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.44",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood Baby & Me 2 Prenatal Multi Vitamins - Prenatal Vitamins for Women with Choline, Methyl Folate & Iron, Vegetarian, Gluten-Free, Pre Natal Multivitamin for Women - 120 Tablets, 60 Servings",
    asin: "B01CQ3E6HG",
    msku: "HRN-B01CQ3E6HG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/baby-me-2-120-tablets/mf-1240",
    amazonUrl: "https://www.amazon.com/dp/B01CQ3E6HG?th=1",
    orderNumber: "WO110074774",
    driveLink: "",
    packCount: 1,
    quantity: 6,
    unitCost: "34.26",
    sellingPrice: "60.00",
    totalCost: "205.58",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 6,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Sipariş satıcı tarafından iptal edildi",
    problemResult: "İade onaylandı",
    refundAmount: "205.58",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "205.58",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Vital Proteins Grass Fed Beef Liver Capsules, Desiccated Liver Supplement, 750mg Liver Pills, 120 Count",
    asin: "B00V7COK0G",
    msku: "FCRB00V7COK0G",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/beef-liver-120-cap/vtp0002",
    amazonUrl: "https://www.amazon.com/dp/B00V7COK0G",
    orderNumber: "WO110074739",
    driveLink: "",
    packCount: 1,
    quantity: 8,
    unitCost: "23.21",
    sellingPrice: "50.00",
    totalCost: "185.70",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 8,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Sipariş stok yetersizliği sebebiyle iptal",
    problemResult: "Tam iade alındı",
    refundAmount: "185.70",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Vital",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.70",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Vital Proteins Collagen Peptides for Women - 20g Hydrolyzed Collagen, Vitamin C, Hyaluronic Acid, Reduce Fine Lines & Wrinkles, Verisol & Holimel - Skin Complex Supplement, Unflavored 11.9oz Powder",
    asin: "B0D19MF171",
    msku: "HRN-B0D19MF171",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/vital-proteins-unflavored-11-9-oz-powder/vtp-13008",
    amazonUrl: "https://www.amazon.com/dp/B0D19MF171",
    orderNumber: "WO110074729",
    driveLink: "",
    packCount: 1,
    quantity: 10,
    unitCost: "16.19",
    sellingPrice: "40.00",
    totalCost: "161.92",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 10,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Adres doğrulama kaynaklı iptal",
    problemResult: "Yeniden sipariş açılacak",
    refundAmount: "161.92",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Vital",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "161.92",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood Baby & Me 2 Prenatal Multi Vitamins - Prenatal Vitamins for Women with Choline, Methyl Folate & Iron, Vegetarian, Gluten-Free, Pre Natal Multivitamin for Women - 120 Tablets, 60 Servings",
    asin: "B01CQ3E6HG",
    msku: "HRN-B01CQ3E6HG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/baby-me-2-120-tablets/mf-1240",
    amazonUrl: "https://www.amazon.com/dp/B01CQ3E6HG?th=1",
    orderNumber: "WO110074759",
    driveLink: "",
    packCount: 1,
    quantity: 6,
    unitCost: "34.26",
    sellingPrice: "60.00",
    totalCost: "205.58",
    orderEmail: "cerberusmay01@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 6,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Satıcı iptali",
    problemResult: "Kart iadesi yapıldı",
    refundAmount: "205.58",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "205.58",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood One Daily Multivitamin - Multivitamin for Women and Men - with Real Food - Immune Support Supplement - Vitamin C & Vitamin B - Bone Health - Energy Metabolism - Vegetarian, Non-GMO - 180 Tabs",
    asin: "B00014DAJ8",
    msku: "MHB00014DAJ8",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/megafood-one-daily-180-tablets/mf-1123",
    amazonUrl: "https://www.amazon.com/dp/B00014DAJ8?th=1",
    orderNumber: "WO110074758",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "46.36",
    sellingPrice: "80.00",
    totalCost: "185.44",
    orderEmail: "cerberusmay01@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "185.44",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.44",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Vital Proteins Collagen Peptides for Women - 20g Hydrolyzed Collagen, Vitamin C, Hyaluronic Acid, Reduce Fine Lines & Wrinkles, Verisol & Holimel - Skin Complex Supplement, Unflavored 11.9oz Powder",
    asin: "B0D19MF171",
    msku: "HRN-B0D19MF171",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/vital-proteins-unflavored-11-9-oz-powder/vtp-13008",
    amazonUrl: "https://www.amazon.com/dp/B0D19MF171",
    orderNumber: "WO110074722",
    driveLink: "",
    packCount: 1,
    quantity: 10,
    unitCost: "16.19",
    sellingPrice: "40.00",
    totalCost: "161.92",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 10,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "161.92",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Vital",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "161.92",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-22",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Vital Proteins Collagen Peptides + Biotin 10000mcg Hair Complex, Hair Growth Supplement - Clinically Studied Lustriva to Promote Thicker Fuller Hair, 20g Unflavored Collagen for Women 11.4oz Powder",
    asin: "B0D19FGYZG",
    msku: "HRN-B0D19FGYZG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/vital-proteins-unflavored-11-41-oz-powder/vtp-13007",
    amazonUrl: "https://www.amazon.com/dp/B0D19FGYZG?th=1",
    orderNumber: "WO110074721",
    driveLink: "",
    packCount: 1,
    quantity: 10,
    unitCost: "16.19",
    sellingPrice: "40.00",
    totalCost: "161.92",
    orderEmail: "cerberusmay01@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 10,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "161.92",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Vital",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "161.92",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood One Daily Multivitamin - Multivitamin for Women and Men - with Real Food - Immune Support Supplement - Vitamin C & Vitamin B - Bone Health - Energy Metabolism - Vegetarian, Non-GMO - 180 Tabs",
    asin: "B00014DAJ8",
    msku: "MHB00014DAJ8",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/megafood-one-daily-180-tablets/mf-1123",
    amazonUrl: "https://www.amazon.com/dp/B00014DAJ8?th=1",
    orderNumber: "WO110074782",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "46.36",
    sellingPrice: "80.00",
    totalCost: "185.44",
    orderEmail: "cerberusnewjersey@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "185.44",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.44",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood Baby & Me 2 Prenatal Multi Vitamins - Prenatal Vitamins for Women with Choline, Methyl Folate & Iron, Vegetarian, Gluten-Free, Pre Natal Multivitamin for Women - 120 Tablets, 60 Servings",
    asin: "B01CQ3E6HG",
    msku: "HRN-B01CQ3E6HG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/baby-me-2-120-tablets/mf-1240",
    amazonUrl: "https://www.amazon.com/dp/B01CQ3E6HG?th=1",
    orderNumber: "WO110074754",
    driveLink: "",
    packCount: 1,
    quantity: 6,
    unitCost: "34.26",
    sellingPrice: "60.00",
    totalCost: "205.58",
    orderEmail: "cerberusnewjersey@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 6,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "205.58",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "205.58",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood One Daily Multivitamin - Multivitamin for Women and Men - with Real Food - Immune Support Supplement - Vitamin C & Vitamin B - Bone Health - Energy Metabolism - Vegetarian, Non-GMO - 180 Tabs",
    asin: "B00014DAJ8",
    msku: "MHB00014DAJ8",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/megafood-one-daily-180-tablets/mf-1123",
    amazonUrl: "https://www.amazon.com/dp/B00014DAJ8?th=1",
    orderNumber: "WO110074751",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "46.36",
    sellingPrice: "80.00",
    totalCost: "185.44",
    orderEmail: "cerberusnewjersey@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "185.44",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.44",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-21",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood Baby & Me 2 Prenatal Multi Vitamins - Prenatal Vitamins for Women with Choline, Methyl Folate & Iron, Vegetarian, Gluten-Free, Pre Natal Multivitamin for Women - 120 Tablets, 60 Servings",
    asin: "B01CQ3E6HG",
    msku: "HRN-B01CQ3E6HG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/baby-me-2-120-tablets/mf-1240",
    amazonUrl: "https://www.amazon.com/dp/B01CQ3E6HG?th=1",
    orderNumber: "WO110074746",
    driveLink: "",
    packCount: 1,
    quantity: 8,
    unitCost: "34.26",
    sellingPrice: "60.00",
    totalCost: "274.11",
    orderEmail: "cerberusnewjersey@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 8,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "274.11",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "274.11",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-12",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "ONNIT Alpha Brain® Nootropic Brain Supplement for Men and Women, IGEN™ Non-GMO Tested, Memory, Mental Clarity, Cognitive Support and Focus Capsules with L-Theanine and Vitamin B6 (90 Count)",
    asin: "B07WP7Q5BF",
    msku: "HRN-B07WP7Q5BF",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/onnit-labs-alpha-brain-90-veggie-caps/onn1002",
    amazonUrl: "http://amazon.com/dp/B07WP7Q5BF?th=1",
    orderNumber: "WO610572666",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "71.99",
    sellingPrice: "80.00",
    totalCost: "287.96",
    orderEmail: "cerberushaziran@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "287.96",
    creditCard: "5686",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "ONNIT",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "287.96",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-23",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood One Daily Multivitamin - Multivitamin for Women and Men - with Real Food - Immune Support Supplement - Vitamin C & Vitamin B - Bone Health - Energy Metabolism - Vegetarian, Non-GMO - 180 Tabs",
    asin: "B00014DAJ8",
    msku: "MHB00014DAJ8",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/megafood-one-daily-180-tablets/mf-1123",
    amazonUrl: "https://www.amazon.com/dp/B00014DAJ8?th=1",
    orderNumber: "WO110075479",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "46.36",
    sellingPrice: "80.00",
    totalCost: "185.44",
    orderEmail: "heyberus@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "185.44",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "O26",
    correctedCost: "185.44",
    pshBatchNo: "PSH-BATCH-2026-01",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-01-23",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "MegaFood Baby & Me 2 Prenatal Multi Vitamins - Prenatal Vitamins for Women with Choline, Methyl Folate & Iron, Vegetarian, Gluten-Free, Pre Natal Multivitamin for Women - 120 Tablets, 60 Servings",
    asin: "B01CQ3E6HG",
    msku: "HRN-B01CQ3E6HG",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/baby-me-2-120-tablets/mf-1240",
    amazonUrl: "https://www.amazon.com/dp/B01CQ3E6HG?th=1",
    orderNumber: "WO110075476",
    driveLink: "https://drive.google.com/file/d/1DoJEF8iYPCRwhT3BTPghTVrdD3C1zWCe/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "34.27",
    sellingPrice: "60.00",
    totalCost: "137.06",
    orderEmail: "heyberus@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "MegaFood",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "137.06",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO310759607",
    driveLink: "https://drive.google.com/file/d/1ptyqmYoPDhgpTH2lrr5ulBdFqU8W4GgK/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "29.99",
    sellingPrice: "65.00",
    totalCost: "119.97",
    orderEmail: "heyberus@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 0,
    p1CancelQty: 0,
    p2MissingQty: 4,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Depo aramasında bulunamadı",
    problemResult: "Depo tazmin talebi açıldı",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "Kayıp Depoya gelmiş",
    description2: "https://tracking.narvar.com/tracking/vitaminshoppe/amazonshipping?tracking_numbers=TBA328539728206&order_number=WO310759608",
    auditNote: "Depoda kayıp",
    periodCode: "Ş26",
    correctedCost: "119.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "DEPO_SAYILDI",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR NAD+ Anti-Aging Supplement (NMN or Nicotinamide Riboside Alternative) with Resveratrol, Astaxanthin, Spermidine & Luteolin Complex to Support Cellular Health & Healthy Aging, 60 Capsules",
    asin: "B0DMTGWTM1",
    msku: "HRN-B0DMTGWTM1",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/nad-longetivity-60-capsules/hfm-13908",
    amazonUrl: "https://www.amazon.com/dp/B0DMTGWTM1",
    orderNumber: "WO310759615",
    driveLink: "https://drive.google.com/file/d/1ptyqmYoPDhgpTH2lrr5ulBdFqU8W4GgK/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "23.99",
    sellingPrice: "40.00",
    totalCost: "95.97",
    orderEmail: "cerberusnurten@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "95.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47RZVR3",
    msku: "HRN-B0D47RZVR3",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-pomegranate-berry-60-soft-chews/hfm-12565",
    amazonUrl: "https://www.amazon.com/dp/B0D47RZVR3?th=1",
    orderNumber: "WO310759625",
    driveLink: "https://drive.google.com/file/d/1bM9VMHSZHc1_UMwOnp6mQlcg07S7wFYj/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "23.99",
    sellingPrice: "40.00",
    totalCost: "95.97",
    orderEmail: "cerberushaziran@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 0,
    p1CancelQty: 0,
    p2MissingQty: 4,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Depo kaybı tespit edildi",
    problemResult: "Kayıp bildirimi yapıldı",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "Kayıp eve gönderildi TBA328539735796",
    description2: "https://tracking.narvar.com/tracking/vitaminshoppe/amazonshipping?tracking_numbers=TBA328539735796&order_number=WO310759625",
    auditNote: "Depoda kayıp",
    periodCode: "Ş26",
    correctedCost: "95.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "DEPO_SAYILDI",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110084924",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "cerberusmart@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Sipariş satıcı iptali",
    problemResult: "Para iadesi onaylandı",
    refundAmount: "107.97",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "ev",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Soft Chews, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Hair Growth Vitamins for Women, Clinically Studied, Mixed Berry, 60 Soft Chews",
    asin: "B0DGR9J7LB",
    msku: "HRN-B0DGR9J7LB",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/force-factor-hair-growth-mixed-berry-60-soft-chews/hfm-13781",
    amazonUrl: "https://www.amazon.com/dp/B0DGR9J7LB?th=1",
    orderNumber: "WO110084929",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "22.94",
    sellingPrice: "40.00",
    totalCost: "91.77",
    orderEmail: "cerberusnewjersey@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "91.77",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "91.77",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110084955",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "davidcrbrs@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "107.97",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "ev",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR NAD+ Anti-Aging Supplement (NMN or Nicotinamide Riboside Alternative) with Resveratrol, Astaxanthin, Spermidine & Luteolin Complex to Support Cellular Health & Healthy Aging, 60 Capsules",
    asin: "B0DMTGWTM1",
    msku: "HRN-B0DMTGWTM1",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/nad-longetivity-60-capsules/hfm-13908",
    amazonUrl: "https://www.amazon.com/dp/B0DMTGWTM1",
    orderNumber: "WO310759752",
    driveLink: "https://drive.google.com/file/d/1bM9VMHSZHc1_UMwOnp6mQlcg07S7wFYj/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "23.99",
    sellingPrice: "40.00",
    totalCost: "95.97",
    orderEmail: "cerberuseylharun@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "95.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Soft Chews, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Hair Growth Vitamins for Women, Clinically Studied, Mixed Berry, 60 Soft Chews",
    asin: "B0DGR9J7LB",
    msku: "HRN-B0DGR9J7LB",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/force-factor-hair-growth-mixed-berry-60-soft-chews/hfm-13781",
    amazonUrl: "https://www.amazon.com/dp/B0DGR9J7LB?th=1",
    orderNumber: "WO110084957",
    driveLink: "",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "cerberusmay01@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 6,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "129.55",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110084960",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "cerberusnurten@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "107.97",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO310755703",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "cerberusnurten@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "107.97",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-11",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110084360",
    driveLink: "",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "cerberusnurten@gmail.com",
    cargoStatus: "İPTAL",
    shippedToAmazon: 0,
    p1CancelQty: 4,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "Bu iptal ancak PSH'da 3 girilmiş",
    problemResult: "Düzeltme yapıldı",
    refundAmount: "107.97",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "bu iptal ancak psh da 3 girilmiş",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "BEKLIYOR",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47RZVR3",
    msku: "HRN-B0D47RZVR3",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-pomegranate-berry-60-soft-chews/hfm-12565",
    amazonUrl: "https://www.amazon.com/dp/B0D47RZVR3?th=1",
    orderNumber: "WO110084963",
    driveLink: "https://drive.google.com/file/d/1qNtDe9jLJhYYr_JKvgHMZ9tfZWYdP0aC/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "cerberusnisan@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 6,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "WO110206198 bu orderla değiştirildi",
    problemResult: "Eşleşti",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "WO110206198  bu orderla değiştirildi",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-13",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110086220",
    driveLink: "https://drive.google.com/file/d/1tSDv7SWdB5jpVYbQURC_nGpk5Y6pphqW/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "26.24",
    sellingPrice: "65.00",
    totalCost: "104.96",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "104.96",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-13",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47Q69VD",
    msku: "HRN-B0D47Q69VD",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-black-cherry-60-soft-chews/hfm-12566",
    amazonUrl: "https://www.amazon.com/dp/B0D47Q69VD?th=1",
    orderNumber: "WO110086212",
    driveLink: "https://drive.google.com/file/d/1FWwwn2KZIg-ZINKhsHbPv_0a3JLFudK5/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "20.32",
    sellingPrice: "40.00",
    totalCost: "121.94",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 0,
    p1CancelQty: 0,
    p2MissingQty: 6,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "https://track.amazon.com/tracking/TBA328602207823",
    problemResult: "Depoda kayıp",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "https://track.amazon.com/tracking/TBA328602207823",
    description2: "",
    auditNote: "Depoda kayıp",
    periodCode: "Ş26",
    correctedCost: "121.94",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "DEPO_SAYILDI",
    inventoryLabStatus: "GIRILMEDI",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Capsules, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Women Hair Growth Vitamins, Clinically Studied, Supports All 4 Stages of Growth, 90ct",
    asin: "B0DGQX1FS7",
    msku: "HRN-B0DGQX1FS7",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/hair-growth-accelerator-90-capsules/hfm-13782",
    amazonUrl: "https://www.amazon.com/dp/B0DGQX1FS7?th=1",
    orderNumber: "WO110085607",
    driveLink: "https://drive.google.com/file/d/1L_SsBbEG8u8F68b1v6ZCsasuCDkhotUp/view?usp=drive_link",
    packCount: 1,
    quantity: 4,
    unitCost: "26.99",
    sellingPrice: "65.00",
    totalCost: "107.97",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "107.97",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Creatine HMB, 5g Creatine Monohydrate Powder, 3g myHMB, Support Muscle, Strength, Energy & Recovery, with AstraGin for Enhanced Absorption, ~30 Servings, Unflavored Powder",
    asin: "B0DLL7MC7L",
    msku: "HRN-B0DLL7MC7L",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/creatine-hmb-240-g-powder/fcs-14434",
    amazonUrl: "https://www.amazon.com/dp/B0DLL7MC7L?th=1",
    orderNumber: "WO110085610",
    driveLink: "https://drive.google.com/file/d/1LYrzP-2gQKNEjwR_BFwTr1AkpF9EqE33/view?usp=drive_link",
    packCount: 1,
    quantity: 4,
    unitCost: "24.29",
    sellingPrice: "50.00",
    totalCost: "97.17",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "97.17",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47Q69VD",
    msku: "HRN-B0D47Q69VD",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-black-cherry-60-soft-chews/hfm-12566",
    amazonUrl: "https://www.amazon.com/dp/B0D47Q69VD?th=1",
    orderNumber: "WO110085608",
    driveLink: "https://drive.google.com/file/d/1ld9DseHVYRLgeUAsxVpLn90vtWFkwYZD/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 6,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47Q69VD",
    msku: "HRN-B0D47Q69VD",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-black-cherry-60-soft-chews/hfm-12566",
    amazonUrl: "https://www.amazon.com/dp/B0D47Q69VD?th=1",
    orderNumber: "WO110085592",
    driveLink: "https://drive.google.com/file/d/1-s5idYwVAVT-WGM4BUmiB9_QQTqZ1yiI/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 6,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Creatine HMB, 5g Creatine Monohydrate Powder, 3g myHMB, Support Muscle, Strength, Energy & Recovery, with AstraGin for Enhanced Absorption, ~30 Servings, Unflavored Powder",
    asin: "B0DLL7MC7L",
    msku: "HRN-B0DLL7MC7L",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/creatine-hmb-240-g-powder/fcs-14434",
    amazonUrl: "https://www.amazon.com/dp/B0DLL7MC7L?th=1",
    orderNumber: "WO110085587",
    driveLink: "https://drive.google.com/file/d/1HEHHhMv30kn44J5Zim0au2iuJKIJ8C7q/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "24.29",
    sellingPrice: "50.00",
    totalCost: "97.17",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "97.17",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Irwin Naturals Prosta-Strong - 180 Softgels - Prostate Health Support with Saw Palmetto, Lycopene & Pumpkin Seed - Supports Urinary Flow",
    asin: "B005S6XGZ2",
    msku: "HRN-B005S6XGZ2",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/irwin-naturals-prosta-strong-vp-180-softgels/in-1100",
    amazonUrl: "https://www.amazon.com/dp/B005S6XGZ2",
    orderNumber: "WO110085580",
    driveLink: "https://drive.google.com/file/d/1kmbmr8PwWHAnD8qGQ1lO2z_PyrjHgH2o/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "37.79",
    sellingPrice: "50.00",
    totalCost: "151.17",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Irwin",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "151.17",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Hair Growth Accelerator Soft Chews, Lustriva & Biotin to Promote Thicker, Stronger, Fuller Hair, Hair Growth Vitamins for Women, Clinically Studied, Mixed Berry, 60 Soft Chews",
    asin: "B0DGR9J7LB",
    msku: "HRN-B0DGR9J7LB",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/force-factor-hair-growth-mixed-berry-60-soft-chews/hfm-13781",
    amazonUrl: "https://www.amazon.com/dp/B0DGR9J7LB?th=1",
    orderNumber: "WO110085573",
    driveLink: "https://drive.google.com/file/d/1Oh4JkmA0mXp3YduaSYSMqYnean6eML4R/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 6,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "Irwin Naturals Prosta-Strong - 180 Softgels - Prostate Health Support with Saw Palmetto, Lycopene & Pumpkin Seed - Supports Urinary Flow",
    asin: "B005S6XGZ2",
    msku: "HRN-B005S6XGZ2",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/irwin-naturals-prosta-strong-vp-180-softgels/in-1100",
    amazonUrl: "https://www.amazon.com/dp/B005S6XGZ2",
    orderNumber: "WO110085567",
    driveLink: "https://drive.google.com/file/d/1nfbcUglAHx1WeuK9uWGtonD1pluVtfXd/view?usp=sharing",
    packCount: 1,
    quantity: 4,
    unitCost: "37.79",
    sellingPrice: "50.00",
    totalCost: "151.17",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 4,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "Irwin",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "151.17",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
  {
    buyerStore: "HRN",
    orderDate: "2026-02-12",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80",
    fulfillmentType: "FBA",
    productTitle: "FORCE FACTOR Total Beets Ultimate Heart Health Blood Pressure Support Chews with CoQ10, Beet Root Powder, Grape Seed Extract, Blood Pressure Supplement for Circulation & Blood Flow, 60 Soft Chews",
    asin: "B0D47RZVR3",
    msku: "HRN-B0D47RZVR3",
    supplierName: "THE VITAMINSHOPPE",
    supplierCode: "A198",
    supplierUrl: "https://www.vitaminshoppe.com/p/total-beets-ultimate-heart-pomegranate-berry-60-soft-chews/hfm-12565",
    amazonUrl: "https://www.amazon.com/dp/B0D47RZVR3?th=1",
    orderNumber: "WO110085563",
    driveLink: "https://drive.google.com/file/d/1vQa3r-fo8_7Y1rAMCrAe7iBjQZmZiwEy/view?usp=sharing",
    packCount: 1,
    quantity: 6,
    unitCost: "21.59",
    sellingPrice: "40.00",
    totalCost: "129.55",
    orderEmail: "adamwrite25@gmail.com",
    cargoStatus: "Tam Geldi",
    shippedToAmazon: 6,
    p1CancelQty: 0,
    p2MissingQty: 0,
    p3DefectiveQty: 0,
    p4ExpiredQty: 0,
    problemAction: "",
    problemResult: "",
    refundAmount: "0.00",
    creditCard: "1753",
    isFragile: "NO",
    isMultiPack: "NO",
    isBundle: "NO",
    condition: "New",
    brandName: "FORCE",
    description1: "",
    description2: "",
    auditNote: "",
    periodCode: "Ş26",
    correctedCost: "129.55",
    pshBatchNo: "PSH-BATCH-2026-02",
    pshStatus: "AMAZONA_SEVK",
    inventoryLabStatus: "AKTIF_SATISTA",
  },
];

export const INITIAL_ORDERS = ALL_38_XLS_ORDERS.map((o, idx) => ({
  id: idx + 1,
  ...o,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}));

export const INITIAL_STORES = [
  {
    id: 1,
    storeCode: "HRN",
    storeName: "HRN Amazon US Storefront",
    marketplace: "AMAZON",
    buyerName: "Harun",
    currency: "USD",
    status: "ACTIVE",
    totalOrdersCount: INITIAL_ORDERS.length,
    totalSpend: INITIAL_ORDERS.reduce((s, o) => s + Number(o.totalCost), 0).toFixed(2),
  },
  {
    id: 2,
    storeCode: "SEL",
    storeName: "Selin Beauty & Health Amazon",
    marketplace: "AMAZON",
    buyerName: "Selin",
    currency: "USD",
    status: "ACTIVE",
    totalOrdersCount: 0,
    totalSpend: "0.00",
  },
  {
    id: 3,
    storeCode: "MK",
    storeName: "Mert Prime Tech Amazon",
    marketplace: "AMAZON",
    buyerName: "Mert",
    currency: "USD",
    status: "ACTIVE",
    totalOrdersCount: 0,
    totalSpend: "0.00",
  },
  {
    id: 4,
    storeCode: "AMZ-02",
    storeName: "Apex Frontier Amazon Store #02",
    marketplace: "AMAZON",
    buyerName: "Operasyon Ekibi",
    currency: "USD",
    status: "ACTIVE",
    totalOrdersCount: 0,
    totalSpend: "0.00",
  },
];

export const INITIAL_BATCHES = [
  {
    id: 1,
    batchNumber: "PSH-BATCH-2026-01",
    storeCode: "HRN",
    title: "Ocak 2026 Vitamin Shoppe Sevkiyatı (14 Sipariş)",
    status: "HAZIRLANIYOR",
    totalItemsCount: 14,
    totalUnitsCount: 80,
    receivedUnitsCount: 4,
    missingUnitsCount: 0,
    defectiveUnitsCount: 0,
    inventoryLabSynced: false,
    notes: "İptal olan siparişler ve ön inceleme ürünleri",
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    batchNumber: "PSH-BATCH-2026-02",
    storeCode: "HRN",
    title: "Şubat 2026 Force Factor & MegaFood FBA Sevkiyatı",
    status: "AMAZONA_GONDERILDI",
    totalItemsCount: 24,
    totalUnitsCount: 124,
    receivedUnitsCount: 104,
    missingUnitsCount: 20,
    defectiveUnitsCount: 0,
    inventoryLabSynced: true,
    notes: "Depoda eksik çıkan ürünler için tazminat ve takip açıldı",
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 1,
    actorName: "Harun (HRN Store)",
    storeCode: "HRN",
    actionType: "XLS_BATCH_IMPORT",
    targetEntity: `HRN Master XLS (${INITIAL_ORDERS.length} Sipariş)`,
    beforeState: "GOOGLE_DRIVE_XLS",
    afterState: "CERBERUS_DATABASE",
    details: "Google Drive XLS tablosundaki 40 kolonlu gerçek siparişler aktarıldı. PSH ve Inventory Lab entegrasyonu sağlandı.",
    createdAt: new Date().toISOString(),
  },
];
