CREATE TABLE "audit_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"actor_name" text NOT NULL,
	"store_code" text DEFAULT 'HRN' NOT NULL,
	"action_type" text NOT NULL,
	"target_entity" text NOT NULL,
	"before_state" text,
	"after_state" text,
	"details" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"buyer_store" text DEFAULT 'HRN' NOT NULL,
	"order_date" text NOT NULL,
	"image_url" text,
	"fulfillment_type" text DEFAULT 'FBA' NOT NULL,
	"product_title" text NOT NULL,
	"asin" text NOT NULL,
	"msku" text NOT NULL,
	"supplier_name" text NOT NULL,
	"supplier_code" text DEFAULT 'A198',
	"supplier_url" text NOT NULL,
	"amazon_url" text NOT NULL,
	"order_number" text NOT NULL,
	"drive_link" text,
	"pack_count" integer DEFAULT 1 NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"unit_cost" numeric(10, 2) NOT NULL,
	"selling_price" numeric(10, 2) NOT NULL,
	"total_cost" numeric(12, 2) NOT NULL,
	"order_email" text NOT NULL,
	"cargo_status" text DEFAULT 'Yolda' NOT NULL,
	"shipped_to_amazon" integer DEFAULT 0 NOT NULL,
	"p1_cancel_qty" integer DEFAULT 0 NOT NULL,
	"p2_missing_qty" integer DEFAULT 0 NOT NULL,
	"p3_defective_qty" integer DEFAULT 0 NOT NULL,
	"p4_expired_qty" integer DEFAULT 0 NOT NULL,
	"problem_action" text,
	"problem_result" text,
	"refund_amount" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"credit_card" text DEFAULT '1753',
	"is_fragile" text DEFAULT 'NO' NOT NULL,
	"is_multipack" text DEFAULT 'NO' NOT NULL,
	"is_bundle" text DEFAULT 'NO' NOT NULL,
	"count_per_bundle" integer,
	"condition" text DEFAULT 'New' NOT NULL,
	"brand_name" text NOT NULL,
	"description_1" text,
	"description_2" text,
	"audit_note" text,
	"period_code" text DEFAULT 'O26',
	"corrected_cost" numeric(12, 2) NOT NULL,
	"psh_batch_no" text,
	"psh_status" text DEFAULT 'BEKLIYOR' NOT NULL,
	"inventory_lab_status" text DEFAULT 'GIRILMEDI' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_masters" (
	"id" serial PRIMARY KEY NOT NULL,
	"product_code" text NOT NULL,
	"title" text NOT NULL,
	"brand" text NOT NULL,
	"category" text NOT NULL,
	"upc" text NOT NULL,
	"asin" text NOT NULL,
	"msku" text NOT NULL,
	"source_url" text NOT NULL,
	"source_domain" text NOT NULL,
	"supplier_name" text NOT NULL,
	"researcher_code" text DEFAULT 'SRC-01' NOT NULL,
	"researcher_name" text NOT NULL,
	"lifecycle_stage" text DEFAULT 'APPROVED' NOT NULL,
	"data_quality_status" text DEFAULT 'VALID' NOT NULL,
	"data_freshness_status" text DEFAULT 'FRESH' NOT NULL,
	"observed_at" timestamp DEFAULT now() NOT NULL,
	"decision_action" text DEFAULT 'BUY' NOT NULL,
	"confidence_score" integer DEFAULT 88 NOT NULL,
	"risk_level" text DEFAULT 'LOW' NOT NULL,
	"policy_status" text DEFAULT 'APPROVED_BY_POLICY' NOT NULL,
	"source_price" numeric(10, 2) NOT NULL,
	"prep_cost" numeric(10, 2) DEFAULT '1.35' NOT NULL,
	"marketplace_fee" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"fulfillment_fee" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"landed_cost" numeric(10, 2) NOT NULL,
	"selling_price" numeric(10, 2) NOT NULL,
	"estimated_net_profit" numeric(10, 2) NOT NULL,
	"roi_percent" numeric(7, 2) NOT NULL,
	"actual_roi_percent" numeric(7, 2),
	"duplicate_score" integer DEFAULT 12 NOT NULL,
	"duplicate_status" text DEFAULT 'CLEAR' NOT NULL,
	"profitability_score" integer DEFAULT 88 NOT NULL,
	"demand_score" integer DEFAULT 92 NOT NULL,
	"competition_score" integer DEFAULT 78 NOT NULL,
	"price_stability_score" integer DEFAULT 85 NOT NULL,
	"supplier_risk_score" integer DEFAULT 94 NOT NULL,
	"operational_risk_score" integer DEFAULT 90 NOT NULL,
	"opportunity_score" integer DEFAULT 88 NOT NULL,
	"evidence_chain" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"channel_listings" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cost_history" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"notes" text,
	"discovered_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "product_masters_product_code_unique" UNIQUE("product_code")
);
--> statement-breakpoint
CREATE TABLE "psh_batches" (
	"id" serial PRIMARY KEY NOT NULL,
	"batch_number" text NOT NULL,
	"store_code" text DEFAULT 'HRN' NOT NULL,
	"title" text NOT NULL,
	"status" text DEFAULT 'HAZIRLANIYOR' NOT NULL,
	"total_items_count" integer DEFAULT 0 NOT NULL,
	"total_units_count" integer DEFAULT 0 NOT NULL,
	"received_units_count" integer DEFAULT 0 NOT NULL,
	"missing_units_count" integer DEFAULT 0 NOT NULL,
	"defective_units_count" integer DEFAULT 0 NOT NULL,
	"inventory_lab_synced" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "psh_batches_batch_number_unique" UNIQUE("batch_number")
);
--> statement-breakpoint
CREATE TABLE "research_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_code" text NOT NULL,
	"researcher_code" text NOT NULL,
	"researcher_name" text NOT NULL,
	"source_domain" text NOT NULL,
	"products_found" integer DEFAULT 0 NOT NULL,
	"products_approved" integer DEFAULT 0 NOT NULL,
	"session_quality_score" integer DEFAULT 90 NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "research_sessions_session_code_unique" UNIQUE("session_code")
);
--> statement-breakpoint
CREATE TABLE "researchers" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"specialty_domain" text NOT NULL,
	"discovery_volume" integer DEFAULT 0 NOT NULL,
	"approval_rate" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"purchase_conversion" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"average_roi" numeric(6, 2) DEFAULT '0.00' NOT NULL,
	"average_net_profit" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"problem_rate" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"researcher_score" integer DEFAULT 85 NOT NULL,
	"active_listings_count" integer DEFAULT 0 NOT NULL,
	"avatar" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "researchers_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "stores" (
	"id" serial PRIMARY KEY NOT NULL,
	"store_code" text NOT NULL,
	"store_name" text NOT NULL,
	"marketplace" text DEFAULT 'AMAZON' NOT NULL,
	"buyer_name" text DEFAULT 'Harun' NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"default_card" text DEFAULT '1753',
	"default_email" text,
	"notes" text,
	"account_health_score" integer DEFAULT 98 NOT NULL,
	"total_orders_count" integer DEFAULT 0 NOT NULL,
	"total_spend" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "stores_store_code_unique" UNIQUE("store_code")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'STORE_USER' NOT NULL,
	"store_code" text DEFAULT 'HRN' NOT NULL,
	"avatar" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_buyer_store_stores_store_code_fk" FOREIGN KEY ("buyer_store") REFERENCES "public"."stores"("store_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_psh_batch_no_psh_batches_batch_number_fk" FOREIGN KEY ("psh_batch_no") REFERENCES "public"."psh_batches"("batch_number") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "orders_order_number_store_uq" ON "orders" USING btree ("order_number","buyer_store");--> statement-breakpoint
CREATE INDEX "orders_buyer_store_date_idx" ON "orders" USING btree ("buyer_store","order_date");--> statement-breakpoint
CREATE INDEX "orders_asin_idx" ON "orders" USING btree ("asin");