"use client";

import { ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter();
  const [show,setShow]=useState(false), [loading,setLoading]=useState(false), [error,setError]=useState("");
  async function submit(form:FormData){setLoading(true);setError("");const response=await fetch("/api/auth/login",{method:"POST",body:JSON.stringify({email:form.get("email"),password:form.get("password")}),headers:{"content-type":"application/json"}});if(response.ok){router.push("/");router.refresh();}else{setError("E-posta veya parola hatalı.");setLoading(false);}}
  return <main className="grid min-h-screen bg-[#07101e] lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 opacity-40 [background-image:radial-gradient(circle_at_20%_20%,#0891b2_0,transparent_28%),radial-gradient(circle_at_80%_80%,#4338ca_0,transparent_30%)]"/><div className="absolute inset-0 opacity-[.08] [background-image:linear-gradient(rgba(255,255,255,.15)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.15)_1px,transparent_1px)] [background-size:42px_42px]"/><div className="relative flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-cyan-400 shadow-[0_8px_35px_rgba(34,211,238,.28)]"><ShieldCheck className="size-6 text-slate-950"/></div><div><div className="text-xl font-bold tracking-[.18em] text-white">CERBERUS</div><div className="text-[9px] uppercase tracking-[.25em] text-slate-500">Commerce Intelligence</div></div></div><div className="relative max-w-xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider text-cyan-300"><Sparkles className="size-3"/>Product intelligence, unified</div><h1 className="text-5xl font-bold leading-[1.08] tracking-tight text-white">Bir ürünü keşiften<br/><span className="bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent">kâra dönüştürün.</span></h1><p className="mt-5 max-w-lg text-sm leading-7 text-slate-400">26 mağazanızı, sourcing ekibinizi ve ticari hafızanızı tek karar merkezinde yönetin.</p><div className="mt-9 grid grid-cols-3 gap-3">{[["128","Yeni keşif"],["26","Aktif mağaza"],["%34.8","Onay oranı"]].map(([v,l])=><div key={l} className="rounded-2xl border border-white/[.08] bg-white/[.04] p-4 backdrop-blur"><div className="text-xl font-bold text-white">{v}</div><div className="mt-1 text-[10px] text-slate-500">{l}</div></div>)}</div></div><p className="relative text-[10px] text-slate-600">© 2026 Cerberus · Product Intelligence & Commerce Operations</p></section>
    <section className="flex items-center justify-center bg-white px-6 py-12"><div className="w-full max-w-[390px]"><div className="mb-10 flex items-center gap-3 lg:hidden"><div className="grid size-10 place-items-center rounded-xl bg-slate-900"><ShieldCheck className="size-5 text-cyan-400"/></div><b className="tracking-[.15em]">CERBERUS</b></div><div className="mb-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-cyan-600">Güvenli çalışma alanı</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Tekrar hoş geldiniz</h2><p className="mt-2 text-sm text-slate-500">Komuta merkezinize devam etmek için giriş yapın.</p></div><form action={submit} className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">E-posta adresi</span><input name="email" type="email" defaultValue="mert@cerberus.io" required className="w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none transition focus:border-cyan-500 focus:ring-4 focus:ring-cyan-500/10"/></label><label className="block"><div className="mb-1.5 flex justify-between"><span className="text-xs font-semibold text-slate-700">Parola</span><button type="button" className="text-[10px] font-semibold text-cyan-600">Parolamı unuttum</button></div><div className="relative"><input name="password" type={show?"text":"password"} defaultValue="cerberus2026" required className="w-full rounded-xl border border-slate-200 px-3.5 py-3 pr-11 text-sm outline-none transition focus:border-cyan-500 focus:ring-4 focus:ring-cyan-500/10"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div></label>{error&&<div className="rounded-xl bg-rose-50 px-3 py-2.5 text-xs font-medium text-rose-700">{error}</div>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 py-3.5 text-xs font-bold text-white shadow-lg shadow-slate-900/15 transition hover:-translate-y-0.5 hover:bg-slate-800 disabled:opacity-60">{loading?<span className="size-4 animate-spin rounded-full border-2 border-white/30 border-t-white"/>:<>Giriş yap <ArrowRight className="size-4"/></>}</button></form><div className="mt-6 rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-500"/><p className="text-[10px] leading-4 text-slate-500"><b className="text-slate-700">Demo hesabı hazır.</b> Yukarıdaki bilgilerle ürün istihbaratı çalışma alanını keşfedebilirsiniz.</p></div></div><div className="mt-8 flex items-center justify-center gap-2 text-[9px] text-slate-400"><LockKeyhole className="size-3"/>256-bit şifreli · RBAC korumalı · Audit log aktif</div></div></section>
  </main>;
}
