import { db } from "@/db";
import {
  users,
  researchers,
  stores,
  suppliers,
  productDiscoveries,
  problems,
  auditLogs,
} from "@/db/schema";
import { count } from "drizzle-orm";

export async function ensureCerberusSeeded() {
  const existingCount = await db
    .select({ total: count() })
    .from(productDiscoveries);

  if (Number(existingCount[0]?.total || 0) > 0) {
    return;
  }

  // 1. Current Users
  await db.insert(users).values([
    {
      name: "Ahmet Erdem (VP Operations)",
      email: "ahmet@cerberus-commerce.io",
      role: "MANAGER",
      avatar: "AE",
    },
    {
      name: "Selin Yilmaz (Lead Sourcing Strategist)",
      email: "selin@cerberus-commerce.io",
      role: "LEAD_SOURCER",
      avatar: "SY",
    },
    {
      name: "Mert Çelik (Senior US Researcher)",
      email: "mert@cerberus-commerce.io",
      role: "RESEARCHER",
      avatar: "MÇ",
    },
  ]);

  // 2. All 10 US Sourcing Intelligence Personnel
  await db.insert(researchers).values([
    {
      code: "SRC-01",
      name: "Ahmet Kaya",
      email: "ahmet.k@cerberus-commerce.io",
      specialtyDomain: "Home Depot & Lowe's Clearance Arbitrage",
      discoveryVolume: 342,
      approvalRate: "78.40",
      purchaseConversion: "64.20",
      averageRoi: "68.40",
      averageNetProfit: "24890.00",
      problemRate: "2.10",
      researcherScore: 94,
      activeListingsCount: 118,
      avatar: "AK",
    },
    {
      code: "SRC-02",
      name: "Selin Yilmaz",
      email: "selin.y@cerberus-commerce.io",
      specialtyDomain: "Target US & Kohl's Beauty & Home",
      discoveryVolume: 298,
      approvalRate: "82.10",
      purchaseConversion: "71.50",
      averageRoi: "74.80",
      averageNetProfit: "31420.00",
      problemRate: "1.40",
      researcherScore: 96,
      activeListingsCount: 142,
      avatar: "SY",
    },
    {
      code: "SRC-03",
      name: "Mert Çelik",
      email: "mert.c@cerberus-commerce.io",
      specialtyDomain: "BestBuy & MicroCenter Electronics",
      discoveryVolume: 265,
      approvalRate: "69.20",
      purchaseConversion: "58.40",
      averageRoi: "54.20",
      averageNetProfit: "19840.00",
      problemRate: "3.20",
      researcherScore: 86,
      activeListingsCount: 94,
      avatar: "MÇ",
    },
    {
      code: "SRC-04",
      name: "Burak Tunç",
      email: "burak.t@cerberus-commerce.io",
      specialtyDomain: "Costco & Sam's Club Bulk Pallets",
      discoveryVolume: 194,
      approvalRate: "84.50",
      purchaseConversion: "76.00",
      averageRoi: "61.90",
      averageNetProfit: "28650.00",
      problemRate: "1.80",
      researcherScore: 91,
      activeListingsCount: 108,
      avatar: "BT",
    },
    {
      code: "SRC-05",
      name: "Zeynep Aksoy",
      email: "zeynep.a@cerberus-commerce.io",
      specialtyDomain: "Ulta Beauty & Sephora Exclusive Sets",
      discoveryVolume: 318,
      approvalRate: "79.80",
      purchaseConversion: "66.90",
      averageRoi: "89.40",
      averageNetProfit: "34910.00",
      problemRate: "1.20",
      researcherScore: 97,
      activeListingsCount: 156,
      avatar: "ZA",
    },
    {
      code: "SRC-06",
      name: "Caner Özkan",
      email: "caner.o@cerberus-commerce.io",
      specialtyDomain: "Grainger & Fastenal Industrial Tools",
      discoveryVolume: 182,
      approvalRate: "75.00",
      purchaseConversion: "62.10",
      averageRoi: "59.30",
      averageNetProfit: "17200.00",
      problemRate: "2.80",
      researcherScore: 84,
      activeListingsCount: 77,
      avatar: "CÖ",
    },
    {
      code: "SRC-07",
      name: "Ece Demir",
      email: "ece.d@cerberus-commerce.io",
      specialtyDomain: "Dick's Sporting Goods & REI Outdoor",
      discoveryVolume: 224,
      approvalRate: "73.20",
      purchaseConversion: "59.80",
      averageRoi: "62.10",
      averageNetProfit: "21450.00",
      problemRate: "2.40",
      researcherScore: 87,
      activeListingsCount: 88,
      avatar: "ED",
    },
    {
      code: "SRC-08",
      name: "Ozan Vural",
      email: "ozan.v@cerberus-commerce.io",
      specialtyDomain: "Macy's & Nordstrom Rack Footwear",
      discoveryVolume: 240,
      approvalRate: "66.50",
      purchaseConversion: "53.20",
      averageRoi: "48.90",
      averageNetProfit: "15340.00",
      problemRate: "4.10",
      researcherScore: 78,
      activeListingsCount: 65,
      avatar: "OV",
    },
    {
      code: "SRC-09",
      name: "Derya Şahin",
      email: "derya.s@cerberus-commerce.io",
      specialtyDomain: "Chewy & Petco High-Velocity Bundles",
      discoveryVolume: 289,
      approvalRate: "81.30",
      purchaseConversion: "68.40",
      averageRoi: "64.70",
      averageNetProfit: "26120.00",
      problemRate: "1.90",
      researcherScore: 92,
      activeListingsCount: 129,
      avatar: "DŞ",
    },
    {
      code: "SRC-10",
      name: "Kaan Mutlu",
      email: "kaan.m@cerberus-commerce.io",
      specialtyDomain: "Wayfair & Bed Bath Kitchen Hardware",
      discoveryVolume: 211,
      approvalRate: "71.00",
      purchaseConversion: "60.40",
      averageRoi: "55.80",
      averageNetProfit: "18920.00",
      problemRate: "2.60",
      researcherScore: 83,
      activeListingsCount: 82,
      avatar: "KM",
    },
  ]);

  // 3. All 26 Multi-Store Fleet (18 Amazon, 2 Walmart, 5 Shopify, 1 Wholesale)
  const storeSeedData = [
    // 18 Amazon Stores
    ...Array.from({ length: 18 }).map((_, i) => ({
      storeCode: `AMZ-US-${String(i + 1).padStart(2, "0")}`,
      storeName: `Amazon Storefront #${String(i + 1).padStart(2, "0")} (${
        ["Apex FBA North", "Vanguard US", "Titan Prime", "Aegis Retail", "Frontier Choice"][i % 5]
      })`,
      marketplace: "AMAZON",
      region: i === 16 || i === 17 ? "CA" : "US",
      currency: i === 16 || i === 17 ? "CAD" : "USD",
      status: i === 6 ? "WARNING" : "ACTIVE",
      activeListings: 140 + i * 18,
      monthlyGrossRevenue: (68400 + i * 12350).toFixed(2),
      monthlyNetProfit: (15200 + i * 2910).toFixed(2),
      accountHealthScore: i === 6 ? 84 : 96 + (i % 4),
    })),
    // 2 Walmart Stores
    {
      storeCode: "WMT-US-01",
      storeName: "Walmart Marketplace Pro #01",
      marketplace: "WALMART",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 214,
      monthlyGrossRevenue: "142890.00",
      monthlyNetProfit: "31840.00",
      accountHealthScore: 98,
    },
    {
      storeCode: "WMT-US-02",
      storeName: "Walmart Express Retail #02",
      marketplace: "WALMART",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 189,
      monthlyGrossRevenue: "118400.00",
      monthlyNetProfit: "26120.00",
      accountHealthScore: 95,
    },
    // 5 Shopify Stores
    {
      storeCode: "SHP-US-01",
      storeName: "Shopify DTC — TechGear Direct",
      marketplace: "SHOPIFY",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 86,
      monthlyGrossRevenue: "92450.00",
      monthlyNetProfit: "24810.00",
      accountHealthScore: 100,
    },
    {
      storeCode: "SHP-US-02",
      storeName: "Shopify DTC — HomeCraft Depot",
      marketplace: "SHOPIFY",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 112,
      monthlyGrossRevenue: "108300.00",
      monthlyNetProfit: "29400.00",
      accountHealthScore: 99,
    },
    {
      storeCode: "SHP-US-03",
      storeName: "Shopify DTC — BeautyLuxe Apothecary",
      marketplace: "SHOPIFY",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 145,
      monthlyGrossRevenue: "134200.00",
      monthlyNetProfit: "38920.00",
      accountHealthScore: 99,
    },
    {
      storeCode: "SHP-US-04",
      storeName: "Shopify DTC — OutdoorSupply Pro",
      marketplace: "SHOPIFY",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 78,
      monthlyGrossRevenue: "76900.00",
      monthlyNetProfit: "19400.00",
      accountHealthScore: 97,
    },
    {
      storeCode: "SHP-US-05",
      storeName: "Shopify DTC — Industrial ToolMaster",
      marketplace: "SHOPIFY",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 64,
      monthlyGrossRevenue: "69800.00",
      monthlyNetProfit: "17850.00",
      accountHealthScore: 98,
    },
    // 1 Wholesale Store
    {
      storeCode: "WHS-B2B-01",
      storeName: "Cerberus Global B2B Wholesale Portal",
      marketplace: "WHOLESALE",
      region: "US",
      currency: "USD",
      status: "ACTIVE",
      activeListings: 430,
      monthlyGrossRevenue: "418600.00",
      monthlyNetProfit: "78200.00",
      accountHealthScore: 100,
    },
  ];
  await db.insert(stores).values(storeSeedData);

  // 4. Suppliers with Intelligence Score (0-100)
  await db.insert(suppliers).values([
    {
      supplierCode: "SUP-HD-US",
      name: "The Home Depot Commercial US",
      website: "https://www.homedepot.com",
      country: "USA",
      supplierScore: 91,
      priceStabilityScore: 88,
      stockReliabilityScore: 93,
      deliveryReliabilityScore: 94,
      returnRatePercent: "1.40",
      totalProductsSourced: 428,
    },
    {
      supplierCode: "SUP-ULTA-US",
      name: "Ulta Beauty Pro Wholesale & Clearance",
      website: "https://www.ulta.com",
      country: "USA",
      supplierScore: 94,
      priceStabilityScore: 91,
      stockReliabilityScore: 95,
      deliveryReliabilityScore: 96,
      returnRatePercent: "0.85",
      totalProductsSourced: 319,
    },
    {
      supplierCode: "SUP-COSTCO-US",
      name: "Costco Business Center Pallets",
      website: "https://www.costcobusinessdelivery.com",
      country: "USA",
      supplierScore: 89,
      priceStabilityScore: 94,
      stockReliabilityScore: 86,
      deliveryReliabilityScore: 91,
      returnRatePercent: "1.20",
      totalProductsSourced: 512,
    },
    {
      supplierCode: "SUP-BESTBUY-US",
      name: "Best Buy Tech Liquidations",
      website: "https://www.bestbuy.com",
      country: "USA",
      supplierScore: 82,
      priceStabilityScore: 79,
      stockReliabilityScore: 83,
      deliveryReliabilityScore: 88,
      returnRatePercent: "2.90",
      totalProductsSourced: 241,
    },
    {
      supplierCode: "SUP-GRAINGER-US",
      name: "W.W. Grainger Industrial Supplies",
      website: "https://www.grainger.com",
      country: "USA",
      supplierScore: 87,
      priceStabilityScore: 86,
      stockReliabilityScore: 89,
      deliveryReliabilityScore: 90,
      returnRatePercent: "1.60",
      totalProductsSourced: 184,
    },
    {
      supplierCode: "SUP-TARGET-US",
      name: "Target Overstock & Salvage Lots",
      website: "https://www.target.com",
      country: "USA",
      supplierScore: 76,
      priceStabilityScore: 68,
      stockReliabilityScore: 74,
      deliveryReliabilityScore: 84,
      returnRatePercent: "3.80",
      totalProductsSourced: 198,
    },
  ]);

  // 5. Product Discoveries — Representing All 13 Stages + Duplicate Detection + Landed Cost + AI Opportunity Scores
  await db.insert(productDiscoveries).values([
    {
      productCode: "CRB-2026-9041",
      title: "DeWalt 20V MAX XR Brushless Cordless Impact Driver Kit (DCF887D2)",
      brand: "DEWALT",
      category: "Power & Hand Tools",
      upc: "885911425129",
      asin: "B0183RLW8A",
      msku: "DWT-20V-IMP-887",
      sourceUrl: "https://www.homedepot.com/p/DEWALT-20V-MAX-XR/206587428",
      sourceDomain: "homedepot.com",
      supplierName: "The Home Depot Commercial US",
      researcherName: "Ahmet Kaya (SRC-01)",
      lifecycleStage: "APPROVED",
      sourcePrice: "99.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.35",
      marketplaceFee: "28.35",
      fulfillmentFee: "7.15",
      otherCost: "0.50",
      landedCost: "136.35",
      sellingPrice: "189.00",
      estimatedNetProfit: "52.65",
      roiPercent: "53.18",
      monthlyEstimatedUnits: 145,
      duplicateScore: 12,
      duplicateStatus: "CLEAR",
      profitabilityScore: 92,
      demandScore: 94,
      competitionScore: 76,
      priceStabilityScore: 88,
      supplierRiskScore: 94,
      operationalRiskScore: 91,
      opportunityScore: 89,
      aiRecommendation: "HIGH_MARGIN_SCALER",
      aiAnalysisNotes:
        "High buy-box stability on AMZ-US-01/03/07 and WMT-US-01. Home Depot bulk price drop 38% below 90-day Amazon average.",
      channelListings: [
        { storeCode: "AMZ-US-01", storeName: "Amazon Storefront #01", price: 189.0, status: "ACTIVE", stock: 65 },
        { storeCode: "AMZ-US-04", storeName: "Amazon Storefront #04", price: 191.5, status: "ACTIVE", stock: 40 },
        { storeCode: "WMT-US-01", storeName: "Walmart Marketplace Pro #01", price: 188.0, status: "ACTIVE", stock: 35 },
        { storeCode: "SHP-US-05", storeName: "Shopify DTC — Industrial ToolMaster", price: 194.0, status: "ACTIVE", stock: 24 },
      ],
      costHistory: [
        { date: "2026-02-01", sourcePrice: 129.0, landedCost: 166.35, sellingPrice: 189.0, roi: 13.6 },
        { date: "2026-02-12", sourcePrice: 114.0, landedCost: 151.35, sellingPrice: 189.0, roi: 24.8 },
        { date: "2026-02-25", sourcePrice: 99.0, landedCost: 136.35, sellingPrice: 189.0, roi: 53.2 },
      ],
    },
    {
      productCode: "CRB-2026-9042",
      title: "La Roche-Posay Anthelios Melt-in Milk Sunscreen SPF 60 (150mL Duo Pack)",
      brand: "LA ROCHE-POSAY",
      category: "Dermatological Skincare",
      upc: "3337875545839",
      asin: "B002CML1XE",
      msku: "LRP-SPF60-MILK-DUO",
      sourceUrl: "https://www.ulta.com/p/anthelios-melt-in-milk-sunscreen-spf-60-xlsImpprod3840051",
      sourceDomain: "ulta.com",
      supplierName: "Ulta Beauty Pro Wholesale & Clearance",
      researcherName: "Zeynep Aksoy (SRC-05)",
      lifecycleStage: "ACTIVE",
      sourcePrice: "24.50",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.10",
      marketplaceFee: "8.70",
      fulfillmentFee: "4.45",
      otherCost: "0.25",
      landedCost: "39.00",
      sellingPrice: "58.00",
      estimatedNetProfit: "19.00",
      roiPercent: "77.55",
      monthlyEstimatedUnits: 320,
      duplicateScore: 8,
      duplicateStatus: "CLEAR",
      profitabilityScore: 94,
      demandScore: 98,
      competitionScore: 82,
      priceStabilityScore: 91,
      supplierRiskScore: 96,
      operationalRiskScore: 93,
      opportunityScore: 92,
      aiRecommendation: "HIGH_MARGIN_SCALER",
      aiAnalysisNotes:
        "Top 0.3% BSR in Beauty. Brand ungated on 14 Amazon stores and Shopify SHP-US-03.",
      channelListings: [
        { storeCode: "AMZ-US-01", storeName: "Amazon Storefront #01", price: 58.0, status: "ACTIVE", stock: 180 },
        { storeCode: "AMZ-US-02", storeName: "Amazon Storefront #02", price: 58.0, status: "ACTIVE", stock: 140 },
        { storeCode: "AMZ-US-08", storeName: "Amazon Storefront #08", price: 57.95, status: "ACTIVE", stock: 110 },
        { storeCode: "SHP-US-03", storeName: "Shopify DTC — BeautyLuxe Apothecary", price: 62.0, status: "ACTIVE", stock: 95 },
      ],
      costHistory: [
        { date: "2026-02-05", sourcePrice: 28.0, landedCost: 42.5, sellingPrice: 58.0, roi: 36.4 },
        { date: "2026-02-19", sourcePrice: 24.5, landedCost: 39.0, sellingPrice: 58.0, roi: 77.5 },
      ],
    },
    {
      productCode: "CRB-2026-9043",
      title: "Ninja CREAMi 7-in-1 Ice Cream & Frozen Treat Maker (NC301 Silver)",
      brand: "NINJA",
      category: "Kitchen & Countertop Appliances",
      upc: "622356565147",
      asin: "B08QX6L29W",
      msku: "NJA-CREAMI-NC301",
      sourceUrl: "https://www.costcobusinessdelivery.com/ninja-creami-7-in-1.html",
      sourceDomain: "costcobusinessdelivery.com",
      supplierName: "Costco Business Center Pallets",
      researcherName: "Burak Tunç (SRC-04)",
      lifecycleStage: "DUPLICATE_CHECK",
      sourcePrice: "124.99",
      sourceShipping: "4.50",
      intlShipping: "0.00",
      prepCost: "2.10",
      marketplaceFee: "33.00",
      fulfillmentFee: "11.20",
      otherCost: "0.80",
      landedCost: "176.59",
      sellingPrice: "219.99",
      estimatedNetProfit: "43.40",
      roiPercent: "34.72",
      monthlyEstimatedUnits: 210,
      duplicateScore: 96,
      duplicateStatus: "EXACT_DUPLICATE",
      matchedProductCode: "CRB-2026-8812 (Selin Yilmaz — Kohl's US Source)",
      profitabilityScore: 79,
      demandScore: 96,
      competitionScore: 64,
      priceStabilityScore: 72,
      supplierRiskScore: 89,
      operationalRiskScore: 84,
      opportunityScore: 76,
      aiRecommendation: "FLAGGED_IP_RISK",
      aiAnalysisNotes:
        "Duplicate detected! Exact UPC 622356565147 previously logged by Selin Y. at $119.99 via Kohl's US Clearance. Recommend merging ASIN master.",
      channelListings: [
        { storeCode: "AMZ-US-03", storeName: "Amazon Storefront #03", price: 219.99, status: "WARNING", stock: 0 },
      ],
      costHistory: [
        { date: "2026-02-26", sourcePrice: 124.99, landedCost: 176.59, sellingPrice: 219.99, roi: 34.7 },
      ],
    },
    {
      productCode: "CRB-2026-9044",
      title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones (Midnight Blue)",
      brand: "SONY",
      category: "Consumer Electronics",
      upc: "027242925184",
      asin: "B0BXSGVQQ3",
      msku: "SNY-XM5-BLUE-US",
      sourceUrl: "https://www.bestbuy.com/site/sony-wh1000xm5/6533158.p",
      sourceDomain: "bestbuy.com",
      supplierName: "Best Buy Tech Liquidations",
      researcherName: "Mert Çelik (SRC-03)",
      lifecycleStage: "ANALYZING",
      sourcePrice: "229.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.75",
      marketplaceFee: "52.35",
      fulfillmentFee: "6.80",
      otherCost: "1.00",
      landedCost: "290.90",
      sellingPrice: "349.00",
      estimatedNetProfit: "58.10",
      roiPercent: "25.37",
      monthlyEstimatedUnits: 190,
      duplicateScore: 42,
      duplicateStatus: "POSSIBLE_MATCH",
      matchedProductCode: "CRB-2025-7790 (Black colorway)",
      profitabilityScore: 78,
      demandScore: 92,
      competitionScore: 68,
      priceStabilityScore: 84,
      supplierRiskScore: 83,
      operationalRiskScore: 86,
      opportunityScore: 81,
      aiRecommendation: "APPROVED_FOR_PURCHASE",
      aiAnalysisNotes:
        "High ASP electronics. Ensure serial capture at Prep Center for refund fraud defense.",
      channelListings: [
        { storeCode: "AMZ-US-05", storeName: "Amazon Storefront #05", price: 349.0, status: "ACTIVE", stock: 40 },
        { storeCode: "SHP-US-01", storeName: "Shopify DTC — TechGear Direct", price: 359.0, status: "ACTIVE", stock: 25 },
      ],
      costHistory: [
        { date: "2026-02-26", sourcePrice: 229.0, landedCost: 290.9, sellingPrice: 349.0, roi: 25.4 },
      ],
    },
    {
      productCode: "CRB-2026-9045",
      title: "Fluke 117 Electricians True RMS Multimeter with Non-Contact Voltage",
      brand: "FLUKE",
      category: "Industrial Test Instruments",
      upc: "095969344849",
      asin: "B000O3LJWU",
      msku: "FLK-117-TRUERMS",
      sourceUrl: "https://www.grainger.com/product/FLUKE-Digital-Multimeter-117-4XD22",
      sourceDomain: "grainger.com",
      supplierName: "W.W. Grainger Industrial Supplies",
      researcherName: "Caner Özkan (SRC-06)",
      lifecycleStage: "PURCHASING",
      sourcePrice: "142.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.25",
      marketplaceFee: "35.25",
      fulfillmentFee: "5.90",
      otherCost: "0.50",
      landedCost: "184.90",
      sellingPrice: "235.00",
      estimatedNetProfit: "50.10",
      roiPercent: "35.28",
      monthlyEstimatedUnits: 88,
      duplicateScore: 11,
      duplicateStatus: "CLEAR",
      profitabilityScore: 86,
      demandScore: 85,
      competitionScore: 88,
      priceStabilityScore: 94,
      supplierRiskScore: 95,
      operationalRiskScore: 92,
      opportunityScore: 89,
      aiRecommendation: "APPROVED_FOR_PURCHASE",
      aiAnalysisNotes:
        "B2B Wholesale + Amazon Business accounts enjoy zero MAP violations and corporate PO volume.",
      channelListings: [
        { storeCode: "AMZ-US-09", storeName: "Amazon Storefront #09", price: 235.0, status: "ACTIVE", stock: 50 },
        { storeCode: "WHS-B2B-01", storeName: "Cerberus Global B2B Wholesale Portal", price: 228.0, status: "ACTIVE", stock: 120 },
      ],
      costHistory: [
        { date: "2026-02-24", sourcePrice: 142.0, landedCost: 184.9, sellingPrice: 235.0, roi: 35.3 },
      ],
    },
    {
      productCode: "CRB-2026-9046",
      title: "Dyson V15 Detect Total Clean Cordless Stick Vacuum Cleaner (Yellow/Nickel)",
      brand: "DYSON",
      category: "Floor Care & Vacuums",
      upc: "885609024881",
      asin: "B09ZVDL7D4",
      msku: "DYS-V15-DETECT-US",
      sourceUrl: "https://www.target.com/p/dyson-v15-detect/-/A-82451992",
      sourceDomain: "target.com",
      supplierName: "Target Overstock & Salvage Lots",
      researcherName: "Selin Yilmaz (SRC-02)",
      lifecycleStage: "REVIEW",
      sourcePrice: "419.00",
      sourceShipping: "12.00",
      intlShipping: "0.00",
      prepCost: "3.50",
      marketplaceFee: "97.50",
      fulfillmentFee: "16.40",
      otherCost: "2.00",
      landedCost: "550.40",
      sellingPrice: "649.99",
      estimatedNetProfit: "99.59",
      roiPercent: "18.09",
      monthlyEstimatedUnits: 65,
      duplicateScore: 19,
      duplicateStatus: "CLEAR",
      profitabilityScore: 71,
      demandScore: 89,
      competitionScore: 61,
      priceStabilityScore: 74,
      supplierRiskScore: 76,
      operationalRiskScore: 72,
      opportunityScore: 74,
      aiRecommendation: "HOLD_FOR_PRICE_DROP",
      aiAnalysisNotes:
        "ROI below 25% policy threshold due to heavy oversized shipping fees. Hold until Target Circle promo drops source price to $379.",
      channelListings: [
        { storeCode: "AMZ-US-07", storeName: "Amazon Storefront #07", price: 649.99, status: "WARNING", stock: 12 },
      ],
      costHistory: [
        { date: "2026-02-26", sourcePrice: 419.0, landedCost: 550.4, sellingPrice: 649.99, roi: 18.1 },
      ],
    },
    {
      productCode: "CRB-2026-9047",
      title: "Osprey Atmos AG 65 Men's Backpacking Pack (Mythical Green - Medium)",
      brand: "OSPREY",
      category: "Outdoor Recreation & Gear",
      upc: "843820138942",
      asin: "B09LSSW88H",
      msku: "OSP-ATMOS-65-GRN",
      sourceUrl: "https://www.rei.com/product/201302/osprey-atmos-ag-65-pack-mens",
      sourceDomain: "rei.com",
      supplierName: "Dick's Sporting Goods & REI Outdoor",
      researcherName: "Ece Demir (SRC-07)",
      lifecycleStage: "LISTING",
      sourcePrice: "189.99",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "2.10",
      marketplaceFee: "45.00",
      fulfillmentFee: "9.80",
      otherCost: "0.75",
      landedCost: "247.64",
      sellingPrice: "340.00",
      estimatedNetProfit: "92.36",
      roiPercent: "62.59",
      monthlyEstimatedUnits: 52,
      duplicateScore: 6,
      duplicateStatus: "CLEAR",
      profitabilityScore: 90,
      demandScore: 84,
      competitionScore: 86,
      priceStabilityScore: 89,
      supplierRiskScore: 92,
      operationalRiskScore: 90,
      opportunityScore: 88,
      aiRecommendation: "HIGH_MARGIN_SCALER",
      aiAnalysisNotes:
        "End-of-season REI clearance with high summer backpacking demand on Amazon & Shopify OutdoorStore.",
      channelListings: [
        { storeCode: "AMZ-US-10", storeName: "Amazon Storefront #10", price: 340.0, status: "ACTIVE", stock: 38 },
        { storeCode: "SHP-US-04", storeName: "Shopify DTC — OutdoorSupply Pro", price: 349.0, status: "ACTIVE", stock: 24 },
      ],
      costHistory: [
        { date: "2026-02-20", sourcePrice: 189.99, landedCost: 247.64, sellingPrice: 340.0, roi: 62.6 },
      ],
    },
    {
      productCode: "CRB-2026-9048",
      title: "Purina Pro Plan High Protein 30/20 Chicken & Rice Dry Dog Food (37.5 lb Bag)",
      brand: "PURINA PRO PLAN",
      category: "Pet Supplies & Nutrition",
      upc: "038100140292",
      asin: "B001VIYCG8",
      msku: "PPP-SPORT-3020-37LB",
      sourceUrl: "https://www.chewy.com/purina-pro-plan-sport-all-life/dp/52431",
      sourceDomain: "chewy.com",
      supplierName: "Chewy Direct & AutoShip Deals",
      researcherName: "Derya Şahin (SRC-09)",
      lifecycleStage: "MONITORING",
      sourcePrice: "48.50",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.90",
      marketplaceFee: "11.25",
      fulfillmentFee: "12.40",
      otherCost: "0.45",
      landedCost: "74.50",
      sellingPrice: "109.99",
      estimatedNetProfit: "35.49",
      roiPercent: "47.64",
      monthlyEstimatedUnits: 410,
      duplicateScore: 10,
      duplicateStatus: "CLEAR",
      profitabilityScore: 88,
      demandScore: 99,
      competitionScore: 72,
      priceStabilityScore: 92,
      supplierRiskScore: 93,
      operationalRiskScore: 89,
      opportunityScore: 88,
      aiRecommendation: "HIGH_MARGIN_SCALER",
      aiAnalysisNotes:
        "Fastest recurring consumable velocity in portfolio (410 units/mo across 6 Amazon stores).",
      channelListings: [
        { storeCode: "AMZ-US-01", storeName: "Amazon Storefront #01", price: 109.99, status: "ACTIVE", stock: 240 },
        { storeCode: "AMZ-US-06", storeName: "Amazon Storefront #06", price: 109.99, status: "ACTIVE", stock: 190 },
        { storeCode: "WMT-US-02", storeName: "Walmart Express Retail #02", price: 108.5, status: "ACTIVE", stock: 120 },
      ],
      costHistory: [
        { date: "2026-02-15", sourcePrice: 48.5, landedCost: 74.5, sellingPrice: 109.99, roi: 47.6 },
      ],
    },
    {
      productCode: "CRB-2026-9049",
      title: "Garmin Fenix 7X Sapphire Solar Multisport GPS Watch (Carbon Gray DLC Titanium)",
      brand: "GARMIN",
      category: "Sports & GPS Wearables",
      upc: "753759278145",
      asin: "B09NMM8S8Z",
      msku: "GRM-FENIX7X-SOLAR",
      sourceUrl: "https://www.bestbuy.com/site/garmin-fenix-7x-sapphire-solar/6494200.p",
      sourceDomain: "bestbuy.com",
      supplierName: "Best Buy Tech Liquidations",
      researcherName: "Mert Çelik (SRC-03)",
      lifecycleStage: "RECEIVED",
      sourcePrice: "520.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.50",
      marketplaceFee: "112.50",
      fulfillmentFee: "7.20",
      otherCost: "1.50",
      landedCost: "642.70",
      sellingPrice: "799.00",
      estimatedNetProfit: "156.30",
      roiPercent: "30.06",
      monthlyEstimatedUnits: 48,
      duplicateScore: 15,
      duplicateStatus: "CLEAR",
      profitabilityScore: 84,
      demandScore: 87,
      competitionScore: 79,
      priceStabilityScore: 86,
      supplierRiskScore: 85,
      operationalRiskScore: 88,
      opportunityScore: 85,
      aiRecommendation: "APPROVED_FOR_PURCHASE",
      aiAnalysisNotes:
        "High-ticket GPS wearable currently received at NJ Main Warehouse ready for FBA case pack labeling.",
      channelListings: [
        { storeCode: "AMZ-US-11", storeName: "Amazon Storefront #11", price: 799.0, status: "ACTIVE", stock: 32 },
        { storeCode: "SHP-US-01", storeName: "Shopify DTC — TechGear Direct", price: 819.0, status: "ACTIVE", stock: 16 },
      ],
      costHistory: [
        { date: "2026-02-23", sourcePrice: 520.0, landedCost: 642.7, sellingPrice: 799.0, roi: 30.1 },
      ],
    },
    {
      productCode: "CRB-2026-9050",
      title: "KitchenAid Artisan Series 5-Quart Tilt-Head Stand Mixer (Imperial Black KSM150PSIB)",
      brand: "KITCHENAID",
      category: "Kitchen & Countertop Appliances",
      upc: "883049244431",
      asin: "B00005UP2P",
      msku: "KAD-ART5QT-BLK",
      sourceUrl: "https://www.homedepot.com/p/KitchenAid-Artisan-Series-5-Qt-Tilt-Head/203204991",
      sourceDomain: "homedepot.com",
      supplierName: "The Home Depot Commercial US",
      researcherName: "Kaan Mutlu (SRC-10)",
      lifecycleStage: "SCREENING",
      sourcePrice: "249.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "2.80",
      marketplaceFee: "67.50",
      fulfillmentFee: "18.90",
      otherCost: "1.20",
      landedCost: "339.40",
      sellingPrice: "449.95",
      estimatedNetProfit: "110.55",
      roiPercent: "32.57",
      monthlyEstimatedUnits: 135,
      duplicateScore: 82,
      duplicateStatus: "REVIEW_REQUIRED",
      matchedProductCode: "CRB-2026-8990 (Matte Black Variant)",
      profitabilityScore: 83,
      demandScore: 93,
      competitionScore: 70,
      priceStabilityScore: 81,
      supplierRiskScore: 92,
      operationalRiskScore: 85,
      opportunityScore: 84,
      aiRecommendation: "APPROVED_FOR_PURCHASE",
      aiAnalysisNotes:
        "Duplicate check flag: check whether UPC matches KSM150PSIB Imperial Black vs Matte Black KSM150PSBM before PO submission.",
      channelListings: [
        { storeCode: "AMZ-US-12", storeName: "Amazon Storefront #12", price: 449.95, status: "ACTIVE", stock: 45 },
        { storeCode: "SHP-US-02", storeName: "Shopify DTC — HomeCraft Depot", price: 459.0, status: "ACTIVE", stock: 30 },
      ],
      costHistory: [
        { date: "2026-02-26", sourcePrice: 249.0, landedCost: 339.4, sellingPrice: 449.95, roi: 32.6 },
      ],
    },
    {
      productCode: "CRB-2026-9051",
      title: "Brooks Ghost 16 Men's Neutral Running Shoes (Black/Ebony 10.5 D US)",
      brand: "BROOKS",
      category: "Footwear & Athletic Apparel",
      upc: "195394208491",
      asin: "B0C9SMG67J",
      msku: "BRK-GHOST16-105D",
      sourceUrl: "https://www.macys.com/shop/product/brooks-mens-ghost-16",
      sourceDomain: "macys.com",
      supplierName: "Macy's & Nordstrom Rack Clearance",
      researcherName: "Ozan Vural (SRC-08)",
      lifecycleStage: "PAUSED",
      sourcePrice: "68.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.40",
      marketplaceFee: "21.00",
      fulfillmentFee: "7.40",
      otherCost: "0.50",
      landedCost: "98.30",
      sellingPrice: "139.99",
      estimatedNetProfit: "41.69",
      roiPercent: "42.41",
      monthlyEstimatedUnits: 72,
      duplicateScore: 14,
      duplicateStatus: "CLEAR",
      profitabilityScore: 82,
      demandScore: 88,
      competitionScore: 59,
      priceStabilityScore: 68,
      supplierRiskScore: 78,
      operationalRiskScore: 75,
      opportunityScore: 75,
      aiRecommendation: "HOLD_FOR_PRICE_DROP",
      aiAnalysisNotes:
        "Return rate spike on footwear (11.4%). Paused restocking on AMZ-US-14 until return inspection completes.",
      channelListings: [
        { storeCode: "AMZ-US-14", storeName: "Amazon Storefront #14", price: 139.99, status: "WARNING", stock: 14 },
      ],
      costHistory: [
        { date: "2026-02-18", sourcePrice: 68.0, landedCost: 98.3, sellingPrice: 139.99, roi: 42.4 },
      ],
    },
    {
      productCode: "CRB-2026-9052",
      title: "Apple AirPods Pro 2nd Gen USB-C MagSafe Case (MTJV3AM/A)",
      brand: "APPLE",
      category: "Consumer Electronics",
      upc: "194253397168",
      asin: "B0D1XD1ZV3",
      msku: "APL-AIRPODSPRO2-USBC",
      sourceUrl: "https://www.costcobusinessdelivery.com/apple-airpods-pro-2nd-gen.html",
      sourceDomain: "costcobusinessdelivery.com",
      supplierName: "Costco Business Center Pallets",
      researcherName: "Burak Tunç (SRC-04)",
      lifecycleStage: "DISCONTINUED",
      sourcePrice: "184.00",
      sourceShipping: "0.00",
      intlShipping: "0.00",
      prepCost: "1.25",
      marketplaceFee: "37.35",
      fulfillmentFee: "4.80",
      otherCost: "0.50",
      landedCost: "227.90",
      sellingPrice: "249.00",
      estimatedNetProfit: "21.10",
      roiPercent: "9.26",
      monthlyEstimatedUnits: 540,
      duplicateScore: 5,
      duplicateStatus: "CLEAR",
      profitabilityScore: 52,
      demandScore: 99,
      competitionScore: 41,
      priceStabilityScore: 62,
      supplierRiskScore: 71,
      operationalRiskScore: 68,
      opportunityScore: 65,
      aiRecommendation: "FLAGGED_IP_RISK",
      aiAnalysisNotes:
        "Discontinued due to Amazon brand gating verification requirements and net ROI dropping under 10%.",
      channelListings: [
        { storeCode: "AMZ-US-15", storeName: "Amazon Storefront #15", price: 249.0, status: "WARNING", stock: 0 },
      ],
      costHistory: [
        { date: "2026-01-20", sourcePrice: 169.0, landedCost: 212.9, sellingPrice: 249.0, roi: 16.9 },
        { date: "2026-02-10", sourcePrice: 184.0, landedCost: 227.9, sellingPrice: 249.0, roi: 9.3 },
      ],
    },
  ]);

  // 6. Operational Problems P1–P4
  await db.insert(problems).values([
    {
      problemCode: "P1-AMZ-007",
      severity: "P1_CRITICAL",
      problemType: "ACCOUNT_ALERT",
      storeCode: "AMZ-US-07",
      storeName: "Amazon Storefront #07 (Titan Prime)",
      productCode: "CRB-2026-9046",
      productTitle: "Dyson V15 Detect Total Clean Cordless Stick Vacuum Cleaner",
      status: "OPEN",
      financialImpact: "4820.00",
      rootCause: "Amazon Account Health Warning: Customer authentic proof request triggered on 3 units shipped via FBA.",
      actionTaken: "Commercial invoice from Target Wholesale submitted to Amazon Seller Performance team via API.",
      assignedTo: "Ahmet Erdem (VP Operations)",
    },
    {
      problemCode: "P2-AMZ-003",
      severity: "P2_HIGH",
      problemType: "PRICE_CHANGE",
      storeCode: "AMZ-US-03",
      storeName: "Amazon Storefront #03 (Vanguard US)",
      productCode: "CRB-2026-9041",
      productTitle: "DeWalt 20V MAX XR Brushless Cordless Impact Driver Kit (DCF887D2)",
      status: "IN_PROGRESS",
      financialImpact: "1450.00",
      rootCause: "Aggressive BuyBox repricer dropped selling price from $189.00 to $168.00 on ASIN B0183RLW8A.",
      actionTaken: "Cerberus Profit Agent locked minimum floor price at $174.50 to preserve 28%+ net ROI.",
      assignedTo: "Selin Yilmaz (Lead Sourcing)",
    },
    {
      problemCode: "P3-WMT-001",
      severity: "P3_MEDIUM",
      problemType: "SUPPLIER_PRICE_INCREASE",
      storeCode: "WMT-US-01",
      storeName: "Walmart Marketplace Pro #01",
      productCode: "CRB-2026-9048",
      productTitle: "Purina Pro Plan High Protein 30/20 Chicken & Rice Dry Dog Food",
      status: "IN_PROGRESS",
      financialImpact: "680.00",
      rootCause: "Chewy AutoShip tier discount updated from 15% to 10% on pallets >20 bags.",
      actionTaken: "Switched secondary sourcing PO to Costco Business Center pallet lot.",
      assignedTo: "Derya Şahin (SRC-09)",
    },
    {
      problemCode: "P4-SHP-003",
      severity: "P4_LOW",
      problemType: "LISTING_ERROR",
      storeCode: "SHP-US-03",
      storeName: "Shopify DTC — BeautyLuxe Apothecary",
      productCode: "CRB-2026-9042",
      productTitle: "La Roche-Posay Anthelios Melt-in Milk Sunscreen SPF 60",
      status: "RESOLVED",
      financialImpact: "120.00",
      rootCause: "Missing secondary lifestyle high-res image on Shopify theme variant gallery.",
      actionTaken: "Synced product master gallery via Cerberus Shopify Adapter.",
      assignedTo: "Zeynep Aksoy (SRC-05)",
      resolvedAt: new Date(),
    },
  ]);

  // 7. Audit Log Trail
  await db.insert(auditLogs).values([
    {
      actorName: "Ahmet Kaya (SRC-01)",
      actorRole: "RESEARCHER",
      actionType: "PRODUCT_DISCOVERY",
      targetEntity: "CRB-2026-9041 (DeWalt DCF887D2)",
      beforeState: "NEW_DISCOVERY",
      afterState: "APPROVED",
      details: "Discovered on homedepot.com at $99.00; AI Opportunity Score 89/100; Approved by Manager.",
    },
    {
      actorName: "Cerberus AI Duplicate Agent",
      actorRole: "AI_AGENT",
      actionType: "DUPLICATE_DETECTION",
      targetEntity: "CRB-2026-9043 (Ninja CREAMi NC301)",
      beforeState: "SCREENING",
      afterState: "EXACT_DUPLICATE (96% Match)",
      details: "Matched UPC 622356565147 with existing Kohl's sourcing entry CRB-2026-8812.",
    },
    {
      actorName: "Selin Yilmaz (Lead Sourcing)",
      actorRole: "LEAD_SOURCER",
      actionType: "STAGE_TRANSITION",
      targetEntity: "CRB-2026-9042 (La Roche-Posay SPF 60)",
      beforeState: "LISTING",
      afterState: "ACTIVE",
      details: "Multi-store listings deployed to AMZ-US-01, AMZ-US-02, AMZ-US-08, and SHP-US-03.",
    },
    {
      actorName: "Ahmet Erdem (VP Operations)",
      actorRole: "MANAGER",
      actionType: "PROBLEM_ESCALATION",
      targetEntity: "P1-AMZ-007 (AMZ-US-07 Account Alert)",
      beforeState: "OPEN",
      afterState: "IN_PROGRESS",
      details: "Submitted Target wholesale invoice verification pack to Amazon Seller Central.",
    },
  ]);
}
